services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
  
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
      - router
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
